"""Shared OpenTelemetry setup for all four A2A services: a manual TracerProvider
fanned out to Phoenix + Langfuse over OTLP HTTP, OpenInference instrumentation
for LangGraph / CrewAI / Google ADK, and baggage promotion.

Call init_observability(service_name) once per process, before any framework
code (LlmAgent, Crew, StateGraph) is constructed -- each server.py's main() does
this as its first line.

Generated by observent.
"""
from __future__ import annotations

import atexit
import base64
import os

from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.processor.baggage import ALLOW_ALL_BAGGAGE_KEYS, BaggageSpanProcessor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

_PROVIDER: TracerProvider | None = None


def _phoenix_exporter() -> OTLPSpanExporter:
    endpoint = os.getenv("PHOENIX_COLLECTOR_ENDPOINT", "http://localhost:6006/v1/traces")
    headers = {}
    if api_key := os.getenv("PHOENIX_API_KEY"):
        headers["Authorization"] = f"Bearer {api_key}"
    return OTLPSpanExporter(endpoint=endpoint, headers=headers or None)


def _langfuse_exporter() -> OTLPSpanExporter | None:
    public_key = os.getenv("LANGFUSE_PUBLIC_KEY")
    secret_key = os.getenv("LANGFUSE_SECRET_KEY")
    if not public_key or not secret_key:
        # Self-hosted Langfuse keys can't be known until the first UI login
        # creates a project (self_host.md § Langfuse) -- skip this exporter
        # rather than fail startup; validate_setup.py flags the missing keys.
        return None
    host = os.getenv("LANGFUSE_BASE_URL", os.getenv("LANGFUSE_HOST", "http://localhost:3000")).rstrip("/")
    auth = base64.b64encode(f"{public_key}:{secret_key}".encode()).decode()
    return OTLPSpanExporter(
        endpoint=f"{host}/api/public/otel/v1/traces",
        headers={"Authorization": f"Basic {auth}"},
    )


def init_observability(service_name: str) -> TracerProvider:
    """Idempotent per-process TracerProvider setup. Returns the existing provider
    on repeat calls within the same process instead of re-instrumenting."""
    global _PROVIDER
    if _PROVIDER is not None:
        return _PROVIDER

    resource_attrs: dict[str, str] = {"service.name": service_name}
    if phoenix_project := os.getenv("PHOENIX_PROJECT_NAME"):
        # Manual multi-backend fan-out never calls phoenix.otel.register(), so
        # PHOENIX_PROJECT_NAME must be folded into the resource instead (see
        # matrix.md § Arize Phoenix) or every trace lands in Phoenix's "default"
        # project.
        resource_attrs["openinference.project.name"] = phoenix_project

    provider = TracerProvider(resource=Resource.create(resource_attrs))
    provider.add_span_processor(BatchSpanProcessor(_phoenix_exporter()))

    langfuse_exporter = _langfuse_exporter()
    if langfuse_exporter is not None:
        provider.add_span_processor(BatchSpanProcessor(langfuse_exporter))

    provider.add_span_processor(BaggageSpanProcessor(ALLOW_ALL_BAGGAGE_KEYS))
    trace.set_tracer_provider(provider)

    from openinference.instrumentation.crewai import CrewAIInstrumentor
    from openinference.instrumentation.google_adk import GoogleADKInstrumentor
    from openinference.instrumentation.langchain import LangChainInstrumentor

    LangChainInstrumentor().instrument(tracer_provider=provider)
    # use_event_listener=True is required for LLM-call spans: CrewAI 1.10+ fires
    # LLM calls through its internal event bus (LLMCallStartedEvent/...), not a
    # wrappable method, so the default (use_event_listener=False) wraps only
    # Crew/Task/Agent/Tool/Memory and never emits an LLM span at all.
    CrewAIInstrumentor().instrument(tracer_provider=provider, use_event_listener=True)
    GoogleADKInstrumentor().instrument(tracer_provider=provider)

    atexit.register(provider.shutdown)
    _PROVIDER = provider
    return provider
