"""Transport-agnostic capture of the input/output that crosses the AI-system
boundary, plus run status, as attributes on the agent run's existing root span.

Shared across all four A2A services (admin, text2sql, rag, deepresearch) in this
monorepo. Works identically whether the agent is triggered by HTTP, a CLI, or a
script: enrich_current_span() stamps onto whatever span is current, and
capture_run() wraps any callable. No web framework required.

Generated by observent. Edit _REDACT_KEYS / _PROMOTE_TO_BAGGAGE / _CONVENTION to
customize; no env-var override is read at runtime by design.
"""
from __future__ import annotations

import functools
import json
from contextlib import nullcontext
from typing import Any, Awaitable, Callable, Iterator, TypeVar

from opentelemetry import baggage, context, trace
from opentelemetry.trace import Status, StatusCode
from opentelemetry.util.types import AttributeValue

_CONVENTION = "both"  # phoenix (OI) + langfuse (OTel-GenAI) fan-out

# Multi-agent identity, generation-time literals used only for the FALLBACK span
# (no framework instrumentor already recording). This module is shared by four
# services on three different frameworks, so each service's wrap point passes its
# own agent_name / agent_role / agent_framework explicitly to open_or_enrich_span
# instead of relying on these generic defaults.
_SERVICE_NAME = "agent"  # names the fallback root span: f"{_SERVICE_NAME}.run"
_AGENT_NAME = "agent"    # agent.name / gen_ai.agent.name on the run's root span
_AGENT_ROLE = ""         # agent.role (OI); "" = omit
_FRAMEWORK = ""          # agent.framework (OI); "" = omit

_REDACT_KEYS: frozenset[str] = frozenset({
    "api_key", "apikey", "api-key",
    "authorization", "bearer",
    "token", "access_token", "refresh_token", "id_token",
    "secret", "client_secret",
    "password", "passwd", "pwd",
    "x-api-key", "x_api_key",
    "openai_api_key", "anthropic_api_key", "azure_openai_key",
    "aws_access_key", "aws_access_key_id",
    "aws_secret", "aws_secret_access_key",
    "cookie", "set-cookie",
    "session", "session_id", "sessionid",
    "csrf", "csrf_token", "x-csrf-token", "xsrf-token",
    "email", "e_mail", "email_address",
    "phone", "phone_number", "mobile",
    "ssn", "social_security_number",
    "credit_card", "card_number", "cvv", "cvc",
    "dob", "date_of_birth", "birth_date",
})
_REDACTED = "***REDACTED***"

# Leaf names promoted from the flattened input into OTel baggage, so a
# BaggageSpanProcessor can stamp them onto every child span.
_PROMOTE_TO_BAGGAGE: frozenset[str] = frozenset({
    "tenant_id",
    "user_id",
    "session_id",
    "request_id",
    "conversation_id",
    "run_id",
    "mcp_session_id",
})

# OTel attribute values must be one of these primitives, or a list of them.
_PRIMITIVES = (str, bool, int, float)

_tracer = trace.get_tracer("observent.capture")

F = TypeVar("F", bound=Callable[..., Any])
AF = TypeVar("AF", bound=Callable[..., Awaitable[Any]])


def _is_sensitive(key: str) -> bool:
    k = key.lower()
    return any(needle in k for needle in _REDACT_KEYS)


def _coerce(value: Any) -> AttributeValue:
    if isinstance(value, _PRIMITIVES):
        return value
    if isinstance(value, (list, tuple)) and all(isinstance(v, _PRIMITIVES) for v in value):
        return list(value)
    return str(value)


def _flatten(prefix: str, value: Any) -> Iterator[tuple[str, AttributeValue]]:
    """Yield (attribute_key, attribute_value) pairs from an arbitrary payload.

    - Dicts recurse with `{prefix}.{key}`. A sensitive key short-circuits to ***REDACTED***.
    - Lists of primitives are kept as a single OTel list attribute.
    - Lists of objects flatten with an integer index segment.
    - None is dropped (OTel disallows None attribute values).
    """
    if value is None:
        return
    if isinstance(value, dict):
        for k, v in value.items():
            child_key = f"{prefix}.{k}" if prefix else str(k)
            if _is_sensitive(str(k)):
                yield child_key, _REDACTED
            else:
                yield from _flatten(child_key, v)
        return
    if isinstance(value, (list, tuple)):
        if all(isinstance(v, _PRIMITIVES) or v is None for v in value):
            cleaned = [v for v in value if v is not None]
            if cleaned:
                yield prefix, _coerce(cleaned)
            return
        for i, v in enumerate(value):
            yield from _flatten(f"{prefix}.{i}", v)
        return
    yield prefix, _coerce(value)


def _promote_baggage(attr_key: str, value: AttributeValue, ctx: context.Context) -> context.Context:
    if value == _REDACTED:
        return ctx
    leaf = attr_key.rsplit(".", 1)[-1]
    if leaf not in _PROMOTE_TO_BAGGAGE:
        return ctx
    return baggage.set_baggage(leaf, str(value), context=ctx)


def _serialize(payload: Any) -> tuple[str, str]:
    """Render `payload` as a single string for `.value` / `gen_ai.*`, alongside its
    mime type. A dict/list becomes valid JSON (`json.dumps`, not Python's `str()`,
    which would emit repr-style single-quoted syntax); a payload that is already a
    string passes through untouched; anything else falls back to `str()`."""
    if isinstance(payload, str):
        return payload, "text/plain"
    if isinstance(payload, (dict, list, tuple)):
        try:
            return json.dumps(payload, default=str, ensure_ascii=False), "application/json"
        except TypeError:
            return str(payload), "text/plain"
    return str(payload), "text/plain"


def _write(span: trace.Span, namespace: str, payload: Any) -> None:
    """Flatten `payload` under `namespace` and set each leaf as a span attribute.

    Also sets the OI-native `input.value` / `output.value` (+ `.mime_type`) and,
    when the convention calls for it, the OTel-GenAI `gen_ai.*` mirror.
    """
    if not span.is_recording():
        return
    ctx = context.get_current()
    # Only recurse into dict/list payloads for per-leaf attributes (input.query,
    # output.reply, ...). A scalar payload (e.g. a plain-string agent output) has
    # no leaves to flatten -- falling through to _flatten's fallback branch would
    # yield a *bare* `namespace` key holding the same content the `.value` mirror
    # below already carries, duplicating a potentially large string on the span.
    if isinstance(payload, (dict, list, tuple)):
        for key, val in _flatten(namespace, payload):
            span.set_attribute(key, val)
            ctx = _promote_baggage(key, val, ctx)
        if ctx is not context.get_current():
            context.attach(ctx)  # promote into the active context for child spans

    # Convention-native single-value mirrors (so each backend's UI lights up).
    flat_str, mime_type = _serialize(payload)
    if _CONVENTION in ("oi", "both"):
        span.set_attribute(f"{namespace}.value", flat_str)
        span.set_attribute(f"{namespace}.mime_type", mime_type)
    if _CONVENTION in ("otel-genai", "both"):
        gen_ai_key = "gen_ai.prompt" if namespace == "input" else "gen_ai.completion"
        span.set_attribute(gen_ai_key, flat_str)


def enrich_current_span(inputs: Any) -> trace.Span:
    """Stamp `input.*` attributes (with redaction + baggage promotion) onto the
    span that is currently recording. Returns that span. Safe to call when no
    span is recording (it becomes a no-op and returns the non-recording span)."""
    span = trace.get_current_span()
    _write(span, "input", inputs)
    return span


def capture_output(result: Any, span: trace.Span | None = None) -> Any:
    """Stamp `output.*` attributes onto `span` (or the current span). Returns the
    result unchanged so it can wrap a return value inline."""
    _write(span or trace.get_current_span(), "output", result)
    return result


def set_ok(span: trace.Span | None = None) -> None:
    span = span or trace.get_current_span()
    if span.is_recording():
        span.set_status(Status(StatusCode.OK))


def set_error(exc: BaseException, span: trace.Span | None = None) -> None:
    span = span or trace.get_current_span()
    if span.is_recording():
        span.record_exception(exc)
        span.set_attribute("error.type", type(exc).__qualname__)
        span.set_status(Status(StatusCode.ERROR, str(exc)))


def _set_agent_identity(
    span: trace.Span,
    agent_name: str | None = None,
    agent_role: str | None = None,
    agent_framework: str | None = None,
) -> None:
    """Stamp the mandatory multi-agent identity attributes onto `span`, per the
    resolved convention. Params override the generation-time literals -- this app
    runs three frameworks across four services on one shared module, so every
    wrap point passes agent_name/agent_role/agent_framework explicitly rather
    than relying on the single _AGENT_NAME/_FRAMEWORK literal pair."""
    if not span.is_recording():
        return
    name = agent_name or _AGENT_NAME
    role = agent_role or _AGENT_ROLE
    framework = agent_framework or _FRAMEWORK
    if _CONVENTION in ("oi", "both"):
        span.set_attribute("openinference.span.kind", "AGENT")
        if name:
            span.set_attribute("agent.name", name)
        if role:
            span.set_attribute("agent.role", role)
        if framework:
            span.set_attribute("agent.framework", framework)
    if _CONVENTION in ("otel-genai", "both"):
        span.set_attribute("gen_ai.operation.name", "invoke_agent")
        if name:
            span.set_attribute("gen_ai.agent.name", name)


def open_or_enrich_span(
    inputs: Any,
    *,
    name: str | None = None,
    agent_name: str | None = None,
    agent_role: str | None = None,
    agent_framework: str | None = None,
):
    """Public context-manager entry point (also used by capture_run / _async).

    If a span is already recording (framework instrumentor / server span), enrich
    it in place and yield it -- **no** new span. Otherwise open a fallback root span
    so input is never missed, named `name` (default `f"{_SERVICE_NAME}.run"`). Either
    way it stamps `input.*` and the multi-agent identity attributes, so the root
    span carries both the run's input and *which* agent produced it. Callers that
    wrap a shared AI boundary (e.g. a base executor) can use this directly instead
    of the decorators; pair it with `capture_output(...)` so the root also carries
    `output.*`."""
    current = trace.get_current_span()
    if current.is_recording():
        enrich_current_span(inputs)
        # Enrich path: the current span belongs to the framework/transport
        # instrumentor, not observent. Only stamp identity when the caller passes
        # it *explicitly* -- never auto-apply the generic literal defaults, which
        # would relabel a foreign span or clobber better identity the instrumentor
        # already set. The fallback span below (which observent owns) always gets
        # identity.
        if agent_name or agent_role or agent_framework:
            _set_agent_identity(current, agent_name, agent_role, agent_framework)
        return nullcontext(current)
    # set_error() already records the exception and sets ERROR status, so disable
    # the context manager's own exception handling to avoid a duplicate event.
    span_name = name or f"{_SERVICE_NAME}.run"
    cm = _tracer.start_as_current_span(
        span_name, record_exception=False, set_status_on_exception=False
    )
    span = cm.__enter__()
    enrich_current_span(inputs)
    _set_agent_identity(span, agent_name, agent_role, agent_framework)
    return _Closing(cm, span)


class _Closing:
    """Adapts start_as_current_span's CM so capture_run can treat both paths alike."""
    def __init__(self, cm: Any, span: trace.Span) -> None:
        self._cm, self.span = cm, span

    def __enter__(self) -> trace.Span:
        return self.span

    def __exit__(self, *exc: Any) -> Any:
        return self._cm.__exit__(*exc)


def capture_run(fn: F) -> F:
    """Decorator: capture the wrapped callable's first argument as `input.*`, its
    return value as `output.*`, and set OK/ERROR status -- on the existing root
    span when one is recording, else on a fallback `agent.run` span.

    Works for sync callables. Use `capture_run_async` for coroutines.
    """
    @functools.wraps(fn)
    def wrapper(*args: Any, **kwargs: Any) -> Any:
        inputs = args[0] if args else kwargs
        holder = open_or_enrich_span(inputs)
        with holder as span:
            try:
                result = fn(*args, **kwargs)
            except BaseException as exc:
                set_error(exc, span)
                raise
            capture_output(result, span)
            set_ok(span)
            return result
    return wrapper  # type: ignore[return-value]


def capture_run_async(fn: AF) -> AF:
    """Async counterpart of capture_run for coroutine entry points."""
    @functools.wraps(fn)
    async def wrapper(*args: Any, **kwargs: Any) -> Any:
        inputs = args[0] if args else kwargs
        holder = open_or_enrich_span(inputs)
        with holder as span:
            try:
                result = await fn(*args, **kwargs)
            except BaseException as exc:
                set_error(exc, span)
                raise
            capture_output(result, span)
            set_ok(span)
            return result
    return wrapper  # type: ignore[return-value]


class TraceContextMiddleware:
    """Extract W3C trace context (traceparent/tracestate) from the incoming
    request so this service's spans join the caller's trace -- WITHOUT opening a
    server span (http_transport_spans: none -- see references/capture.md). Opens
    a lone `http.error` span only if the app raises before the agent boundary's
    own root span exists."""
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        from opentelemetry import context as otel_context
        from opentelemetry.propagate import extract

        carrier = {k.decode("latin-1"): v.decode("latin-1") for k, v in scope.get("headers", [])}
        token = otel_context.attach(extract(carrier))
        try:
            await self.app(scope, receive, send)  # success: no span opened
        except Exception as exc:
            with _tracer.start_as_current_span("http.error") as span:
                span.record_exception(exc)
                span.set_attribute("error.type", type(exc).__qualname__)
                span.set_status(Status(StatusCode.ERROR, str(exc)))
            raise
        finally:
            otel_context.detach(token)
